from enum import Enum

class Languages(Enum):
    ENG = "English"
    GER = "German"
    FRA = "French"
    SPA = "Spanish"
    ITA = "Italian"
    JPN = "Japanese"
    CHN = "Chinese"
    RUS = "Russian"
    ARA = "Arabic"
    POR = "Portuguese"
    HIN = "Hindi"
    BEN = "Bengali"
    KOR = "Korean"
    TUR = "Turkish"
    DUT = "Dutch"
    POL = "Polish"
    UKR = "Ukrainian"
    SWE = "Swedish"
    DAN = "Danish"
    FIN = "Finnish"
    NOR = "Norwegian"
